// Pure formatting for "Export highlights to note" -- and for the same shapes
// the highlights modal copies to the clipboard. No Obsidian or DOM imports, so
// it's directly unit-testable; the caller supplies the already-built Markdown
// links (only Obsidian can resolve those) and writes the file.

export const EXPORT_BEGIN = '%%study-pdf:begin%%';
export const EXPORT_END = '%%study-pdf:end%%';

export interface PaletteColor {
	name: string;
	/** e.g. "#ffeb3b" */
	hex: string;
}

export interface ExportEntry {
	/** 1-based, as shown to the user. */
	pageNumber: number;
	quote: string;
	note: string | null;
	/** As read from the annotation, e.g. "rgb(255, 255, 0)". */
	colorCss: string;
	/** Markdown link to this annotation, alias already sanitized. */
	link: string;
}

const SWATCH_BY_COLOR_NAME: Record<string, string> = {
	Yellow: '🟡',
	Red: '🔴',
	Orange: '🟠',
	Green: '🟢',
	Purple: '🟣',
};

/** Where a PDF's exported highlights live: a sibling note, so the pair travels
 * together when the PDF is moved into a subject folder. `folderPath` is the
 * PDF's parent path -- Obsidian's vault root is '/', which must not become a
 * leading slash in a vault-relative path. */
export function siblingNotePath(
	folderPath: string | undefined,
	basename: string,
	suffix: string,
): string {
	const folder = folderPath && folderPath !== '/' ? `${folderPath}/` : '';
	return `${folder}${basename} (${suffix}).md`;
}

export function exportNotePath(folderPath: string | undefined, basename: string): string {
	return siblingNotePath(folderPath, basename, 'highlights');
}

/** Obsidian deep link subpath for one highlight. Annotation ids come from
 * pdf.js and can go stale when the file is re-saved, hence the page fallback. */
export function annotationSubpath(pageNumber: number, annotationId: string | null): string {
	return annotationId ? `#page=${pageNumber}&annotation=${annotationId}` : `#page=${pageNumber}`;
}

/** Makes recovered PDF text safe to use as a link alias. `[`, `]`, `|`, `(`
 * and `)` all terminate a wikilink or Markdown link early, and quoted text
 * routinely contains them ("as shown in [12]"). Obsidian sanitizes the path it
 * generates, never the display text, so this has to happen here. */
export function sanitizeLinkAlias(text: string): string {
	return text.replace(/[[\]|()]/g, ' ').replace(/\s+/g, ' ').trim();
}

function cssColorToHex(colorCss: string): string | null {
	const match = /^rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/.exec(colorCss.trim());
	if (!match) return null;
	return (
		'#' +
		match
			.slice(1)
			.map((n) => Number(n).toString(16).padStart(2, '0'))
			.join('')
	);
}

/** Emoji swatch for a highlight color, or null when it isn't one of ours.
 * Deliberately an exact match: highlights made in other readers use arbitrary
 * colors, and naming the "nearest" one would confidently mislabel them. */
export function colorSwatch(colorCss: string, palette: PaletteColor[]): string | null {
	const hex = cssColorToHex(colorCss);
	if (!hex) return null;
	const name = palette.find((c) => c.hex.toLowerCase() === hex)?.name;
	return (name && SWATCH_BY_COLOR_NAME[name]) ?? null;
}

/** Builds the Markdown link for one highlight, given whatever the host uses to
 * generate links (Obsidian's `fileManager.generateMarkdownLink`, curried by the
 * caller with the source file and path). Kept here, callback and all, so the
 * alias sanitizing and the empty-quote fallback can't drift between the two
 * call sites that need them. */
export function buildEntryLink(
	entry: { pageNumber: number; quote: string; annotationId: string | null },
	generate: (subpath: string, alias: string) => string,
): string {
	const alias = sanitizeLinkAlias(entry.quote) || `p. ${entry.pageNumber}`;
	return generate(annotationSubpath(entry.pageNumber, entry.annotationId), alias);
}

/** One highlight as Markdown: the text (or a link to it) as a blockquote, with
 * the note as a plain paragraph beneath. Shared with the modal's copy buttons
 * so exported and copied highlights look identical. */
export function formatQuoteBlock(head: string, note: string | null): string {
	return note ? `> ${head}\n\n${note}` : `> ${head}`;
}

/** The managed body: everything between the markers. Regenerated wholesale on
 * every export -- see mergeExportedNote. */
export function formatExportBody(
	entries: ExportEntry[],
	options: { sourceLink: string; palette: PaletteColor[] },
): string {
	const lines = [
		`Highlights from ${options.sourceLink}.`,
		'',
		'This block is regenerated by *Export highlights to note* — re-run it after ' +
			'changing highlights. Edits inside the block are lost; anything outside ' +
			'it is kept.',
	];

	if (entries.length === 0) {
		lines.push('', 'No highlights in this PDF yet.');
		return lines.join('\n');
	}

	let currentPage: number | null = null;
	for (const entry of entries) {
		if (entry.pageNumber !== currentPage) {
			currentPage = entry.pageNumber;
			lines.push('', `## Page ${entry.pageNumber}`);
		}
		const swatch = colorSwatch(entry.colorCss, options.palette);
		lines.push('', formatQuoteBlock(swatch ? `${swatch} ${entry.link}` : entry.link, entry.note));
	}
	return lines.join('\n');
}

/** Splices a freshly generated body into an existing note.
 *
 * Only ever replaces text *between* a well-formed marker pair. A half-deleted
 * block (one marker, or the two in the wrong order) falls back to appending a
 * new block: getting a duplicate block is a nuisance, but a regex that
 * "replaces to the end" would silently delete everything the user wrote after
 * the surviving marker. */
export function mergeExportedNote(existing: string | null, body: string): string {
	const block = `${EXPORT_BEGIN}\n${body}\n${EXPORT_END}`;
	if (!existing?.trim()) return `${block}\n`;

	const begin = existing.indexOf(EXPORT_BEGIN);
	const end = existing.indexOf(EXPORT_END, begin + EXPORT_BEGIN.length);
	if (begin !== -1 && end !== -1) {
		return existing.slice(0, begin) + block + existing.slice(end + EXPORT_END.length);
	}
	return `${existing.trimEnd()}\n\n${block}\n`;
}
